version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_USER: 'vannguyen'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - db

  proxy:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server